version: "2"

services:
  mariadb:
    image: wodby/drupal-mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # The simple way to override the mariadb config.
    volumes:
      - ./docker-runtime/mariadb:/var/lib/mysql
#      - ./docker-runtime/mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  php:
    image: riccardoravaro/drupal-php:7.0 
    environment:
      PHP_SITE_NAME: dev
      PHP_HOST_NAME: localhost:8000
#      PHP_DOCROOT: public # Relative path inside the /var/www/html/ directory.
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG_ENABLED: 0 # Set 1 to enable.
      PHP_XDEBUG_AUTOSTART: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 1
      PHP_XDEBUG_REMOTE_HOST: "localhost"
    volumes:
      - ./docroot:/var/www/html
    links:
      - memcached:memcached

  nginx:
    image: wodby/drupal-nginx
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_UPSTREAM_NAME: php
      NGINX_DOCROOT: web # Relative path inside the /var/www/html/ directory.
      DRUPAL_VERSION: 8 # Allowed: 7, 8.
    volumes_from:
      - php
    ports:
      - "8000:80"
    links:
      - memcached:memcached

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8001:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8002:8025"

#  redis:
#    image: redis:3.2-alpine

  memcached:
    image: memcached:1.4-alpine
    ports:
      - "11211:11211"

  memcached-admin:
    image: phynias/phpmemcachedadmin
    ports:
      - "8006:80"
    links:
      - memcached:memcached

  solr:
    image: solr:5.5-alpine
    volumes:
      - ./docker-runtime/solr:/opt/solr/server/solr/mycores
    ports:
      - "8003:8983"

  varnish:
    image: wodby/drupal-varnish
    depends_on:
      - nginx
    environment:
      VARNISH_SECRET: secret
      VARNISH_BACKEND_HOST: nginx
      VARNISH_BACKEND_PORT: 80
      VARNISH_MEMORY_SIZE: 256M
      VARNISH_STORAGE_SIZE: 1024M
    ports:
      - "8004:6081" # HTTP Proxy
      - "8005:6082" # Control terminal
